"""Write the cross-language reference fixture.

The token format is defined once, in `orgtree/refs.py`, and parsed twice — the
backend emits, the browser resolves. Two parsers are two chances to disagree,
and a disagreement is a link that opens the wrong thing or nothing at all.

So the cases live in one JSON file that BOTH sides test against:

    python backend/tools/gen_ref_fixture.py

`test_refs.py` asserts the committed file still matches what the Python parser
does today, so it cannot rot silently; `frontend/tests/docketrefs.test.tsx`
asserts the TypeScript parser agrees with the file. Neither side can drift
without a red test.
"""
from __future__ import annotations

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
BACKEND = os.path.dirname(HERE)
sys.path.insert(0, BACKEND)

from orgtree import refs                                          # noqa: E402

OUT = os.path.join(os.path.dirname(BACKEND), "frontend", "tests",
                   "ref-tokens.json")

#: every case both parsers must agree on. Valid ones first, then the
#: malformations that must produce nothing — the second half is the half that
#: matters, because "parses as something plausible" is the failure mode.
TOKENS = [
    "@item:alpha/git-review-workspace",
    "@item:beta/git-review-workspace",
    "@item:alpha/w1234abcd",
    "@doc:alpha/d1a2b3c4",
    "@agent:alpha/luna-reserve",
    "@mail:alpha/user/ab12cd34",
    "@mail:alpha/org/ab12cd34",
    "@mail:alpha/node/luna-reserve/ab12cd34",
    # a KNOWLEDGE BEARER: `<name>@<generation>` is a real, addressable node id
    "@agent:alpha/codex-checklist@4",
    "@mail:alpha/node/codex-checklist@4/ab12cd34",
    "@item:alpha/not-a-node@4",
    "@mail:user/user/ab12cd34",
    # malformed: each is refused, never guessed
    "@item:only-one-segment",
    "@item:a/b/c",
    "@mail:org/node/abc",
    "@mail:org/mailbox/abc",
    "@mail:org/user",
    "@nope:org/thing",
    "item:org/thing",
    "@item:Org/Thing",
    "@item:org/thing/",
    "@item:org/",
    "@",
    "",
]

#: prose the matcher must split identically on both sides
PROSE = [
    "see @item:alpha/git-review-workspace, then @mail:alpha/user/ab12. done",
    "`@doc:alpha/d1a2b3c4` in backticks is still a mention",
    "not-a-token@item:alpha/thing is attached to a word",
    "https://x.dev/@item:alpha/thing is a URL",
    "@item:alpha/thing.",
    "@item:alpha/thing.json",
    "two @agent:alpha/one and @agent:alpha/two together",
    "ask @agent:alpha/codex-checklist@4 about it",
    "@agent:a/b@2@item:a/c",
]


def build() -> dict[str, object]:
    return {
        "_note": "generated by backend/tools/gen_ref_fixture.py — both parsers "
                 "test against this; do not hand-edit",
        "parse": {t: refs.parse(t) for t in TOKENS},
        "prose": {p: [list(m) for m in refs.find_all(p)] for p in PROSE},
    }


if __name__ == "__main__":
    blob = json.dumps(build(), indent=2, sort_keys=True) + "\n"
    with open(OUT, "w", encoding="utf-8", newline="\r\n") as f:
        f.write(blob)
    print(f"wrote {OUT} ({len(blob)} bytes, {len(TOKENS)} tokens, "
          f"{len(PROSE)} prose cases)")
